export const blocks = [
  ["Stone_JE4_BE2.png", 1, "minecraft:stone", ["S", "B"]],
  ["Grass_Block_JE8_BE5.png", 2, "minecraft:grass", []],
  ["Dirt_JE2_BE1.png", 3, "minecraft:dirt", ["S", "B"]],
  ["Cobblestone_JE6_BE3.png", 4, "minecraft:cobblestone", []],
  ["Oak_Planks_JE4_BE2.png", 5, "minecraft:planks", ["S", "B"]],
  ["Oak_Sapling_JE5_BE2.png", 6, "minecraft:sapling", ["S", "B"]],
  ["Bedrock_JE2_BE2.png", 7, "minecraft:bedrock", []],
  ["Water.png", 8, "minecraft:flowing_water", ["S"]],
  ["Water.png", 9, "minecraft:water", ["S"]],
  ["Lava.png", 10, "minecraft:flowing_lava", ["S"]],
  ["Lava.png", 11, "minecraft:lava", ["S"]],
  ["Sand_JE5_BE2.png", 12, "minecraft:sand", ["S", "B"]],
  ["Gravel_JE5_BE3.png", 13, "minecraft:gravel", []],
  ["Gold_Ore_JE3_BE2.png", 14, "minecraft:gold_ore", []],
  ["Iron_Ore_JE3.png", 15, "minecraft:iron_ore", []],
  ["Coal_Ore_JE2_BE2.png", 16, "minecraft:coal_ore", []],
  ["Oak_Log_Axis_Y_JE5_BE3.png", 17, "minecraft:log", ["S", "B"]],
  ["Oak_Leaves_JE3_BE1.png", 18, "minecraft:leaves", ["S", "B"]],
  ["Sponge_JE3_BE3.png", 19, "minecraft:sponge", ["S", "B"]],
  ["Glass.png", 20, "minecraft:glass", []],
  ["Lapis_Lazuli_Ore_JE2_BE2.png", 21, "minecraft:lapis_ore", []],
  ["Lapis_Lazuli_Block_JE3_BE3.png", 22, "minecraft:lapis_block", []],
  ["Dispenser_JE3_BE2.png", 23, "minecraft:dispenser", ["S", "E"]],
  ["Sandstone_JE6_BE2.png", 24, "minecraft:sandstone", ["S", "B"]],
  ["Note_Block.png", 25, "minecraft:noteblock", ["E"]],
  ["Red_Bed_JE4_BE3.png", 26, "minecraft:bed", ["I", "S"]],
  ["Powered_Rail.png", 27, "minecraft:golden_rail", ["S"]],
  ["Detector_Rail.png", 28, "minecraft:detector_rail", ["S"]],
  ["Sticky_Piston_JE2.png", 29, "minecraft:sticky_piston", ["S"]],
  ["Cobweb_JE1_BE1.png", 30, "minecraft:web", []],
  ["Grass_JE3_BE2.png", 31, "minecraft:tallgrass", ["S", "B"]],
  ["Dead_Bush_JE2_BE2.png", 32, "minecraft:deadbush", []],
  ["Piston_JE2.png", 33, "minecraft:piston", ["S"]],
  ["Piston_Head_JE2.png", 34, "minecraft:piston_head", ["S"]],
  ["White_Wool.png", 35, "minecraft:wool", ["S", "B"]],
  ["Dandelion_JE2_BE2.png", 37, "minecraft:yellow_flower", []],
  ["Poppy_JE3_BE2.png", 38, "minecraft:red_flower", ["S", "B"]],
  ["Brown_Mushroom_JE2_BE2.png", 39, "minecraft:brown_mushroom", []],
  ["Red_Mushroom_JE2_BE2.png", 40, "minecraft:red_mushroom", []],
  ["Block_of_Gold_JE6_BE3.png", 41, "minecraft:gold_block", []],
  ["Block_of_Iron_JE4_BE3.png", 42, "minecraft:iron_block", []],
  ["Double_Smooth_Stone_Slab_JE2_BE2.png", 43, "minecraft:double_stone_slab", ["S", "B"]],
  ["Smooth_Stone_Slab_JE2_BE2.png", 44, "minecraft:stone_slab", ["S", "B"]],
  ["Bricks_JE5_BE3.png", 45, "minecraft:brick_block", []],
  ["TNT_JE2_BE2.png", 46, "minecraft:tnt", []],
  ["Bookshelf_JE4_BE2.png", 47, "minecraft:bookshelf", []],
  ["Mossy_Cobblestone_JE4_BE2.png", 48, "minecraft:mossy_cobblestone", []],
  ["Obsidian_JE3_BE2.png", 49, "minecraft:obsidian", []],
  ["Torch_JE4_BE2.png", 50, "minecraft:torch", ["S"]],
  ["Fire.png", 51, "minecraft:fire", ["S"]],
  ["Spawner_JE3.png", 52, "minecraft:mob_spawner", ["E"]],
  ["Oak_Stairs_JE7_BE6.png", 53, "minecraft:oak_stairs", ["S"]],
  ["Chest.png", 54, "minecraft:chest", ["S", "E"]],
  ["Inactive_Redstone_Wire_(unconnected)_JE2.png", 55, "minecraft:redstone_wire", ["I", "S"]],
  ["Diamond_Ore_JE3_BE3.png", 56, "minecraft:diamond_ore", []],
  ["Block_of_Diamond_JE6_BE3.png", 57, "minecraft:diamond_block", []],
  ["Crafting_Table_JE4.png", 58, "minecraft:crafting_table", []],
  ["Wheat_Age_7_JE4_BE2.png", 59, "minecraft:wheat", ["I", "S"]],
  ["Farmland_JE4_BE4.png", 60, "minecraft:farmland", ["S"]],
  ["Furnace_JE3_BE2.png", 61, "minecraft:furnace", ["S", "E"]],
  ["Lit_Furnace_JE3_BE2.png", 62, "minecraft:lit_furnace", ["S", "E"]],
  ["Oak_Standing_Sign.png", 63, "minecraft:standing_sign", ["I", "S", "E"]],
  ["Oak_Door_JE5_BE2.png", 64, "minecraft:wooden_door", ["I", "S"]],
  ["Ladder_JE3_BE2.png", 65, "minecraft:ladder", ["S"]],
  ["Rail_(NS).png", 66, "minecraft:rail", ["S"]],
  ["Cobblestone_Stairs_JE6_BE6.png", 67, "minecraft:stone_stairs", ["S"]],
  ["Oak_Wall_Sign.png", 68, "minecraft:wall_sign", ["I", "S", "E"]],
  ["Lever_JE3_BE2.png", 69, "minecraft:lever", ["S"]],
  ["Stone_Pressure_Plate.png", 70, "minecraft:stone_pressure_plate", ["S"]],
  ["Iron_Door_JE2_BE3.png", 71, "minecraft:iron_door", ["I", "S"]],
  ["Oak_Pressure_Plate.png", 72, "minecraft:wooden_pressure_plate", ["S"]],
  ["Redstone_Ore_JE2_BE2.png", 73, "minecraft:redstone_ore", []],
  ["Redstone_Ore_JE2_BE2.png", 74, "minecraft:lit_redstone_ore", []],
  ["Unlit_Redstone_Torch_JE2.png", 75, "minecraft:unlit_redstone_torch", ["S"]],
  ["Redstone_Torch_JE2.png", 76, "minecraft:redstone_torch", ["S"]],
  ["Stone_Button.png", 77, "minecraft:stone_button", ["S"]],
  ["Snow_JE2_BE2.png", 78, "minecraft:snow_layer", ["S", "B"]],
  ["Ice_JE2_BE4.png", 79, "minecraft:ice", []],
  ["Snow_Block_JE2_BE2.png", 80, "minecraft:snow", []],
  ["Cactus_JE4.png", 81, "minecraft:cactus", ["S"]],
  ["Clay_Block_JE2_BE2.png", 82, "minecraft:clay", []],
  ["Sugar_Cane.png", 83, "minecraft:reeds", ["I", "S"]],
  ["Jukebox_JE2_BE2.png", 84, "minecraft:jukebox", ["S", "E"]],
  ["Oak_Fence_JE4_BE2.png", 85, "minecraft:fence", []],
  ["Carved_Pumpkin_JE3_BE2.png", 86, "minecraft:pumpkin", ["S"]],
  ["Netherrack_JE4_BE2.png", 87, "minecraft:netherrack", []],
  ["Soul_Sand_JE2_BE2.png", 88, "minecraft:soul_sand", []],
  ["Glowstone_JE4_BE2.png", 89, "minecraft:glowstone", []],
  ["Nether_Portal.png", 90, "minecraft:portal", ["N"]],
  ["Jack_o'Lantern_JE3_BE2.png", 91, "minecraft:lit_pumpkin", ["S"]],
  ["Cake_JE2.png", 92, "minecraft:cake", ["I", "S"]],
  ["Redstone_Repeater_JE3_BE2.png", 93, "minecraft:unpowered_repeater", ["I", "S"]],
  ["Active_Redstone_Repeater_JE3_BE2.png", 94, "minecraft:powered_repeater", ["I", "S"]],
  ["White_Stained_Glass.png", 95, "minecraft:stained_glass", ["S", "B"]],
  ["Oak_Trapdoor.png", 96, "minecraft:trapdoor", ["S"]],
  ["Stone_JE4_BE2.png", 97, "minecraft:monster_egg", ["S", "B"]],
  ["Stone_Bricks_JE3_BE2.png", 98, "minecraft:stonebrick", ["S", "B"]],
  ["Brown_Mushroom_Block_JE2_BE2.png", 99, "minecraft:brown_mushroom_block", ["S"]],
  ["Red_Mushroom_Block_JE2_BE2.png", 100, "minecraft:red_mushroom_block", ["S"]],
  ["Iron_Bars_(EW)_JE3_BE2.png", 101, "minecraft:iron_bars", []],
  ["Glass_Pane.png", 102, "minecraft:glass_pane", []],
  ["Melon_JE2_BE2.png", 103, "minecraft:melon_block", []],
  ["Stem_Age_7_JE1_BE1.png", 104, "minecraft:pumpkin_stem", ["S"]],
  ["Stem_Age_7_JE1_BE1.png", 105, "minecraft:melon_stem", ["S"]],
  ["Vines_JE2_BE2.png", 106, "minecraft:vine", ["S"]],
  ["Oak_Fence_Gate_JE4_BE2.png", 107, "minecraft:fence_gate", ["S"]],
  ["Brick_Stairs_JE3_BE2.png", 108, "minecraft:brick_stairs", ["S"]],
  ["Stone_Brick_Stairs_JE3_BE2.png", 109, "minecraft:stone_brick_stairs", ["S"]],
  ["Mycelium_JE2_BE2.png", 110, "minecraft:mycelium", []],
  ["Lily_Pad_JE2_BE2.png", 111, "minecraft:waterlily", []],
  ["Nether_Bricks_JE3_BE4.png", 112, "minecraft:nether_brick", []],
  ["Nether_Brick_Fence_JE3_BE4.png", 113, "minecraft:nether_brick_fence", []],
  ["Nether_Brick_Stairs_JE3_BE2.png", 114, "minecraft:nether_brick_stairs", ["S"]],
  ["Nether_Wart.png", 115, "minecraft:nether_wart", ["I", "S"]],
  ["Enchanting_Table_JE4_BE2.png", 116, "minecraft:enchanting_table", ["E"]],
  ["Brewing_Stand.png", 117, "minecraft:brewing_stand", ["I", "S", "E"]],
  ["Cauldron.png", 118, "minecraft:cauldron", ["I", "S"]],
  ["End_Portal.png", 119, "minecraft:end_portal", ["E"]],
  ["End_Portal_Frame_JE2_BE2.png", 120, "minecraft:end_portal_frame", ["S"]],
  ["End_Stone_JE3_BE2.png", 121, "minecraft:end_stone", []],
  ["Dragon_Egg_JE1_BE1.png", 122, "minecraft:dragon_egg", []],
  ["Redstone_Lamp_JE3_BE2.png", 123, "minecraft:redstone_lamp", []],
  ["Lit_Redstone_Lamp_JE3_BE2.png", 124, "minecraft:lit_redstone_lamp", []],
  ["Oak_Planks_JE4_BE2.png", 125, "minecraft:double_wooden_slab", ["S", "B"]],
  ["Oak_Slab_JE5_BE2.png", 126, "minecraft:wooden_slab", ["S", "B"]],
  ["Cocoa_Age_2_JE2_BE2.png", 127, "minecraft:cocoa", ["I", "S"]],
  ["Sandstone_Stairs_JE6_BE3.png", 128, "minecraft:sandstone_stairs", ["S"]],
  ["Emerald_Ore_JE2_BE2.png", 129, "minecraft:emerald_ore", []],
  ["Ender_Chest_JE2_BE2.png", 130, "minecraft:ender_chest", ["S", "E"]],
  ["Tripwire_Hook_JE5_BE2.png", 131, "minecraft:tripwire_hook", ["S"]],
  ["Tripwire.png", 132, "minecraft:tripwire", ["I", "S"]],
  ["Block_of_Emerald_JE4_BE3.png", 133, "minecraft:emerald_block", []],
  ["Spruce_Stairs_JE4_BE2.png", 134, "minecraft:spruce_stairs", ["S"]],
  ["Birch_Stairs_JE3_BE2.png", 135, "minecraft:birch_stairs", ["S"]],
  ["Jungle_Stairs_JE3_BE2.png", 136, "minecraft:jungle_stairs", ["S"]],
  ["Impulse_Command_Block_JE5_BE2.png", 137, "minecraft:command_block", ["E"]],
  ["Beacon_JE6_BE2.png", 138, "minecraft:beacon", ["E"]],
  ["Cobblestone_Wall.png", 139, "minecraft:cobblestone_wall", ["S", "B"]],
  ["Flower_Pot_JE2_BE2.png", 140, "minecraft:flower_pot", ["I", "S", "E"]],
  ["Carrot_JE3_BE2.png", 141, "minecraft:carrots", ["I", "S"]],
  ["Potatoes_Age_3_JE2_BE2.png", 142, "minecraft:potatoes", ["I", "S"]],
  ["Oak_Button.png", 143, "minecraft:oak_button", ["S"]],
  ["Skeleton_Skull.png", 144, "minecraft:skull", ["I", "S", "E"]],
  ["Anvil_JE2_BE2.png", 145, "minecraft:anvil", ["S", "B"]],
  ["Trapped_Chest.png", 146, "minecraft:trapped_chest", ["S", "E"]],
  ["Light_Weighted_Pressure_Plate.png", 147, "minecraft:light_weighted_pressure_plate", ["S"]],
  ["Heavy_Weighted_Pressure_Plate.png", 148, "minecraft:heavy_weighted_pressure_plate", ["S"]],
  ["Redstone_Comparator.png", 149, "minecraft:unpowered_comparator", ["I", "S"]],
  ["Active_Redstone_Comparator.png", 150, "minecraft:powered_comparator", ["S"]],
  ["Daylight_Detector_JE1_BE1.png", 151, "minecraft:daylight_detector", ["E"]],
  ["Block_of_Redstone_JE2_BE2.png", 152, "minecraft:redstone_block", []],
  ["Nether_Quartz_Ore_JE3_BE2.png", 153, "minecraft:quartz_ore", []],
  ["Hopper_(D).png", 154, "minecraft:hopper", ["S", "E"]],
  ["Block_of_Quartz_JE3_BE2.png", 155, "minecraft:quartz_block", ["S", "B"]],
  ["Quartz_Stairs_JE3_BE2.png", 156, "minecraft:quartz_stairs", ["S"]],
  ["Texture_Update_Activator_Rail.png", 157, "minecraft:activator_rail", ["S"]],
  ["Dropper_JE2_BE2.png", 158, "minecraft:dropper", ["S", "E"]],
  ["White_Terracotta_JE1_BE1.png", 159, "minecraft:stained_hardened_clay", ["S", "B"]],
  ["White_Stained_Glass_Pane_JE3_BE2.png", 160, "minecraft:stained_glass_pane", ["S", "B"]],
  ["Oak_Leaves_JE3_BE1.png", 161, "minecraft:leaves2", ["S", "B"]],
  ["Acacia_Log_Axis_Y_JE5_BE3.png", 162, "minecraft:log2", ["S", "B"]],
  ["Acacia_Stairs_JE3_BE2.png", 163, "minecraft:acacia_stairs", ["S"]],
  ["Dark_Oak_Stairs_JE3_BE2.png", 164, "minecraft:dark_oak_stairs", ["S"]],
  ["Slime_Block_JE2_BE3.png", 165, "minecraft:slime", []],
  ["Barrier_JE2_BE2.png", 166, "minecraft:barrier", []],
  ["Iron_Trapdoor.png", 167, "minecraft:iron_trapdoor", ["S"]],
  ["Prismarine_JE2_BE2.png", 168, "minecraft:prismarine", ["S", "B"]],
  ["Sea_Lantern_JE1_BE1.png", 169, "minecraft:sea_lantern", []],
  ["Hay_Bale_Axis_Y_JE2_BE2.png", 170, "minecraft:hay_block", ["S"]],
  ["White_Carpet.png", 171, "minecraft:carpet", ["S", "B"]],
  ["Terracotta_JE2_BE2.png", 172, "minecraft:hardened_clay", []],
  ["Block_of_Coal_JE3_BE2.png", 173, "minecraft:coal_block", []],
  ["Packed_Ice_JE2_BE3.png", 174, "minecraft:packed_ice", []],
  ["Sunflower_JE2_BE2.png", 175, "minecraft:double_plant", ["S", "B"]],
  ["Free-standing_Banner_(Small).png", 176, "minecraft:standing_banner", ["I", "S", "E"]],
  ["Wall-mounted_Banner_(Small).png", 177, "minecraft:wall_banner", ["I", "S", "E"]],
  ["Inverted_Daylight_Detector_JE1_BE1.png", 178, "minecraft:daylight_detector_inverted", ["E"]],
  ["Red_Sandstone_JE4_BE2.png", 179, "minecraft:red_sandstone", ["S", "B"]],
  ["Red_Sandstone_Stairs_JE4_BE2.png", 180, "minecraft:red_sandstone_stairs", ["S"]],
  ["Red_Sandstone_JE4_BE2.png", 181, "minecraft:double_stone_slab2", ["S"]],
  ["Red_Sandstone_Slab_JE4_BE2.png", 182, "minecraft:stone_slab2", ["S"]],
  ["Spruce_Fence_Gate_JE4_BE2.png", 183, "minecraft:spruce_fence_gate", []],
  ["Birch_Fence_Gate_JE3_BE2.png", 184, "minecraft:birch_fence_gate", []],
  ["Jungle_Fence_Gate_JE3_BE2.png", 185, "minecraft:jungle_fence_gate", []],
  ["Dark_Oak_Fence_Gate_JE3_BE2.png", 186, "minecraft:dark_oak_fence_gate", []],
  ["Acacia_Fence_Gate_JE3_BE2.png", 187, "minecraft:acacia_fence_gate", []],
  ["Spruce_Fence_JE4_BE2.png", 188, "minecraft:spruce_fence", []],
  ["Birch_Fence_JE3_BE2.png", 189, "minecraft:birch_fence", []],
  ["Jungle_Fence_JE3_BE2.png", 190, "minecraft:jungle_fence", []],
  ["Dark_Oak_Fence_JE3_BE2.png", 191, "minecraft:dark_oak_fence", []],
  ["Acacia_Fence_JE3_BE2.png", 192, "minecraft:acacia_fence", []],
  ["Spruce_Door_JE3_BE2.png", 193, "minecraft:spruce_door", ["I", "S"]],
  ["Birch_Door_JE3_BE2.png", 194, "minecraft:birch_door", ["I", "S"]],
  ["Jungle_Door_JE4_BE2.png", 195, "minecraft:jungle_door", ["I", "S"]],
  ["Acacia_Door_JE4_BE2.png", 196, "minecraft:acacia_door", ["I", "S"]],
  ["Dark_Oak_Door_JE3_BE2.png", 197, "minecraft:dark_oak_door", ["I", "S"]],
  ["End_Rod_JE2_BE2.png", 198, "minecraft:end_rod", []],
  ["Chorus_Plant_JE2_BE2.png", 199, "minecraft:chorus_plant", []],
  ["Chorus_Flower_JE2_BE2.png", 200, "minecraft:chorus_flower", []],
  ["Purpur_Block_JE2_BE2.png", 201, "minecraft:purpur_block", []],
  ["Purpur_Pillar_Axis_Y_JE3_BE2.png", 202, "minecraft:purpur_pillar", []],
  ["Purpur_Stairs_JE2_BE2.png", 203, "minecraft:purpur_stairs", []],
  ["Purpur_Block_JE2_BE2.png", 204, "minecraft:purpur_double_slab", []],
  ["Purpur_Slab_JE2_BE2.png", 205, "minecraft:purpur_slab", []],
  ["End_Stone_Bricks_JE2_BE2.png", 206, "minecraft:end_bricks", []],
  ["Beetroots_Age_3_JE2_BE2.png", 207, "minecraft:beetroots", []],
  ["Grass_Path_JE2_BE2.png", 208, "minecraft:grass_path", []],
  ["End_Gateway_JE2_BE1.png", 209, "minecraft:end_gateway", []],
  ["Repeating_Command_Block_JE4_BE2.png", 210, "minecraft:repeating_command_block", ["E"]],
  ["Chain_Command_Block_JE3_BE2.png", 211, "minecraft:chain_command_block", ["E"]],
  ["Ice_JE2_BE4.png", 212, "minecraft:frosted_ice", ["S"]],
  ["Magma_Block_JE2_BE2.png", 213, "minecraft:magma", []],
  ["Nether_Wart_Block_JE3_BE3.png", 214, "minecraft:nether_wart_block", []],
  ["Red_Nether_Bricks_JE3_BE2.png", 215, "minecraft:red_nether_brick", []],
  ["Bone_Block_Axis_Y_JE2_BE2.png", 216, "minecraft:bone_block", []],
  ["Structure_Void_JE2.png", 217, "minecraft:structure_void", []],
  ["Observer_JE4_BE3.png", 218, "minecraft:observer", []],
  ["White_Shulker_Box.png", 219, "minecraft:white_shulker_box", []],
  ["Orange_Shulker_Box.png", 220, "minecraft:orange_shulker_box", []],
  ["Magenta_Shulker_Box.png", 221, "minecraft:magenta_shulker_box", []],
  ["Light_Blue_Shulker_Box.png", 222, "minecraft:light_blue_shulker_box", []],
  ["Yellow_Shulker_Box.png", 223, "minecraft:yellow_shulker_box", []],
  ["Lime_Shulker_Box.png", 224, "minecraft:lime_shulker_box", []],
  ["Pink_Shulker_Box.png", 225, "minecraft:pink_shulker_box", []],
  ["Gray_Shulker_Box.png", 226, "minecraft:gray_shulker_box", []],
  ["Light_Gray_Shulker_Box.png", 227, "minecraft:silver_shulker_box", []],
  ["Cyan_Shulker_Box.png", 228, "minecraft:cyan_shulker_box", []],
  ["Purple_Shulker_Box.png", 229, "minecraft:purple_shulker_box", []],
  ["Blue_Shulker_Box.png", 230, "minecraft:blue_shulker_box", []],
  ["Brown_Shulker_Box.png", 231, "minecraft:brown_shulker_box", []],
  ["Green_Shulker_Box.png", 232, "minecraft:green_shulker_box", []],
  ["Red_Shulker_Box.png", 233, "minecraft:red_shulker_box", []],
  ["Black_Shulker_Box.png", 234, "minecraft:black_shulker_box", []],
  ["White_Glazed_Terracotta.png", 235, "minecraft:white_glazed_terracotta", []],
  ["Orange_Glazed_Terracotta.png", 236, "minecraft:orange_glazed_terracotta", []],
  ["Magenta_Glazed_Terracotta.png", 237, "minecraft:magenta_glazed_terracotta", []],
  ["Light_Blue_Glazed_Terracotta.png", 238, "minecraft:light_blue_glazed_terracotta", []],
  ["Yellow_Glazed_Terracotta.png", 239, "minecraft:yellow_glazed_terracotta", []],
  ["Lime_Glazed_Terracotta.png", 240, "minecraft:lime_glazed_terracotta", []],
  ["Pink_Glazed_Terracotta.png", 241, "minecraft:pink_glazed_terracotta", []],
  ["Gray_Glazed_Terracotta.png", 242, "minecraft:gray_glazed_terracotta", []],
  ["Light_Gray_Glazed_Terracotta.png", 243, "minecraft:silver_glazed_terracotta", []],
  ["Cyan_Glazed_Terracotta.png", 244, "minecraft:cyan_glazed_terracotta", []],
  ["Purple_Glazed_Terracotta.png", 245, "minecraft:purple_glazed_terracotta", []],
  ["Blue_Glazed_Terracotta.png", 246, "minecraft:blue_glazed_terracotta", []],
  ["Brown_Glazed_Terracotta.png", 247, "minecraft:brown_glazed_terracotta", []],
  ["Green_Glazed_Terracotta.png", 248, "minecraft:green_glazed_terracotta", []],
  ["Red_Glazed_Terracotta.png", 249, "minecraft:red_glazed_terracotta", []],
  ["Black_Glazed_Terracotta.png", 250, "minecraft:black_glazed_terracotta", []],
  ["White_Concrete.png", 251, "minecraft:concrete", ["S"]],
  ["White_Concrete_Powder.png", 252, "minecraft:concrete_powder", ["S"]],
  ["Structure_Block_Save_JE2_BE1.png", 255, "minecraft:structure_block", ["S", "E"]]
];

export const items = [
  [[-32, -80], 256, "minecraft:iron_shovel", ["D"]],
  [[-32, -96], 257, "minecraft:iron_pickaxe", ["D"]],
  [[-32, -112], 258, "minecraft:iron_axe", ["D"]],
  [[-80, 0], 259, "minecraft:flint_and_steel", ["D"]],
  [[-160, 0], 260, "minecraft:apple", []],
  [[-80, -16], 261, "minecraft:bow", ["D"]],
  [[-80, -32], 262, "minecraft:arrow", []],
  [[-112, 0], 263, "minecraft:coal", ["B"]],
  [[-112, -48], 264, "minecraft:diamond", []],
  [[-112, -16], 265, "minecraft:iron_ingot", []],
  [[-112, -32], 266, "minecraft:gold_ingot", []],
  [[-32, -64], 267, "minecraft:iron_sword", ["D"]],
  [[0, -64], 268, "minecraft:wooden_sword", ["D"]],
  [[0, -80], 269, "minecraft:wooden_shovel", ["D"]],
  [[0, -96], 270, "minecraft:wooden_pickaxe", ["D"]],
  [[0, -112], 271, "minecraft:wooden_axe", ["D"]],
  [[-16, -64], 272, "minecraft:stone_sword", ["D"]],
  [[-16, -80], 273, "minecraft:stone_shovel", ["D"]],
  [[-16, -96], 274, "minecraft:stone_pickaxe", ["D"]],
  [[-16, -112], 275, "minecraft:stone_axe", ["D"]],
  [[-48, -64], 276, "minecraft:diamond_sword", ["D"]],
  [[-48, -80], 277, "minecraft:diamond_shovel", ["D"]],
  [[-48, -96], 278, "minecraft:diamond_pickaxe", ["D"]],
  [[-48, -112], 279, "minecraft:diamond_axe", ["D"]],
  [[-80, -48], 280, "minecraft:stick", []],
  [[-112, -64], 281, "minecraft:bowl", []],
  [[-128, -64], 282, "minecraft:mushroom_stew", []],
  [[-64, -64], 283, "minecraft:golden_sword", ["D"]],
  [[-64, -80], 284, "minecraft:golden_shovel", ["D"]],
  [[-64, -96], 285, "minecraft:golden_pickaxe", ["D"]],
  [[-64, -112], 286, "minecraft:golden_axe", ["D"]],
  [[-128, 0], 287, "minecraft:string", []],
  [[-128, -16], 288, "minecraft:feather", []],
  [[-128, -32], 289, "minecraft:gunpowder", []],
  [[0, -128], 290, "minecraft:wooden_hoe", ["D"]],
  [[-16, -128], 291, "minecraft:stone_hoe", ["D"]],
  [[-32, -128], 292, "minecraft:iron_hoe", ["D"]],
  [[-48, -128], 293, "minecraft:diamond_hoe", ["D"]],
  [[-64, -128], 294, "minecraft:golden_hoe", ["D"]],
  [[-144, 0], 295, "minecraft:wheat_seeds", []],
  [[-144, -16], 296, "minecraft:wheat", []],
  [[-144, -32], 297, "minecraft:bread", []],
  [[0, -224], 298, "minecraft:leather_helmet", ["D"]],
  [[-16, -224], 299, "minecraft:leather_chestplate", ["D"]],
  [[-32, -224], 300, "minecraft:leather_leggings", ["D"]],
  [[-48, -224], 301, "minecraft:leather_boots", ["D"]],
  [[-16, 0], 302, "minecraft:chainmail_helmet", ["D"]],
  [[-16, -16], 303, "minecraft:chainmail_chestplate", ["D"]],
  [[-16, -32], 304, "minecraft:chainmail_leggings", ["D"]],
  [[-16, -48], 305, "minecraft:chainmail_boots", ["D"]],
  [[-32, 0], 306, "minecraft:iron_helmet", ["D"]],
  [[-32, -16], 307, "minecraft:iron_chestplate", ["D"]],
  [[-32, -32], 308, "minecraft:iron_leggings", ["D"]],
  [[-32, -48], 309, "minecraft:iron_boots", ["D"]],
  [[-48, 0], 310, "minecraft:diamond_helmet", ["D"]],
  [[-48, -16], 311, "minecraft:diamond_chestplate", ["D"]],
  [[-48, -32], 312, "minecraft:diamond_leggings", ["D"]],
  [[-48, -48], 313, "minecraft:diamond_boots", ["D"]],
  [[-64, 0], 314, "minecraft:golden_helmet", ["D"]],
  [[-64, -16], 315, "minecraft:golden_chestplate", ["D"]],
  [[-64, -32], 316, "minecraft:golden_leggings", ["D"]],
  [[-64, -48], 317, "minecraft:golden_boots", ["D"]],
  [[-96, 0], 318, "minecraft:flint", []],
  [[-112, -80], 319, "minecraft:porkchop", []],
  [[-128, -80], 320, "minecraft:cooked_porkchop", []],
  [[-160, -16], 321, "minecraft:painting", []],
  [[-176, 0], 322, "minecraft:golden_apple", ["B"]],
  [[-160, -32], 323, "minecraft:sign", []],
  [[-176, -32], 324, "minecraft:wooden_door", []],
  [[-160, -64], 325, "minecraft:bucket", []],
  [[-176, -64], 326, "minecraft:water_bucket", []],
  [[-192, -64], 327, "minecraft:lava_bucket", []],
  [[-112, -128], 328, "minecraft:minecart", []],
  [[-128, -96], 329, "minecraft:saddle", []],
  [[-192, -32], 330, "minecraft:iron_door", []],
  [[-128, -48], 331, "minecraft:redstone", []],
  [[-224, 0], 332, "minecraft:snowball", []],
  [[0, -256], 333, "minecraft:boat", []],
  [[-112, -96], 334, "minecraft:leather", []],
  [[-208, -64], 335, "minecraft:milk_bucket", []],
  [[-96, -16], 336, "minecraft:brick", []],
  [[-144, -48], 337, "minecraft:clay_ball", []],
  [[-176, -16], 338, "minecraft:reeds", []],
  [[-160, -48], 339, "minecraft:paper", []],
  [[-176, -48], 340, "minecraft:book", []],
  [[-224, -16], 341, "minecraft:slime_ball", []],
  [[-112, -144], 342, "minecraft:chest_minecart", []],
  [[-112, -160], 343, "minecraft:furnace_minecart", []],
  [[-192, 0], 344, "minecraft:egg", []],
  [[-96, -48], 345, "minecraft:compass", []],
  [[-80, -64], 346, "minecraft:fishing_rod", ["D"]],
  [[-96, -64], 347, "minecraft:clock", []],
  [[-144, -64], 348, "minecraft:glowstone_dust", []],
  [[-144, -80], 349, "minecraft:fish", ["B"]],
  [[-160, -80], 350, "minecraft:cooked_fish", ["B"]],
  [[-224, -64], 351, "minecraft:dye", ["B"]],
  [[-192, -16], 352, "minecraft:bone", []],
  [[-208, 0], 353, "minecraft:sugar", []],
  [[-208, -16], 354, "minecraft:cake", []],
  [[-208, -32], 355, "minecraft:bed", ["B"]],
  [[-96, -80], 356, "minecraft:repeater", []],
  [[-192, -80], 357, "minecraft:cookie", []],
  [[-192, -48], 358, "minecraft:filled_map", ["B"]],
  [[-208, -80], 359, "minecraft:shears", ["D"]],
  [[-208, -96], 360, "minecraft:melon", []],
  [[-208, -48], 361, "minecraft:pumpkin_seeds", []],
  [[-224, -48], 362, "minecraft:melon_seeds", []],
  [[-144, -96], 363, "minecraft:beef", []],
  [[-160, -96], 364, "minecraft:cooked_beef", []],
  [[-144, -112], 365, "minecraft:chicken", []],
  [[-160, -112], 366, "minecraft:cooked_chicken", []],
  [[-176, -80], 367, "minecraft:rotten_flesh", []],
  [[-176, -96], 368, "minecraft:ender_pearl", []],
  [[-192, -96], 369, "minecraft:blaze_rod", []],
  [[-176, -112], 370, "minecraft:ghast_tear", []],
  [[-192, -112], 371, "minecraft:gold_nugget", []],
  [[-208, -112], 372, "minecraft:nether_wart", []],
  [[-208, -128], 373, "minecraft:potion", ["B"]],
  [[-192, -128], 374, "minecraft:glass_bottle", []],
  [[-176, -128], 375, "minecraft:spider_eye", []],
  [[-160, -128], 376, "minecraft:fermented_spider_eye", []],
  [[-208, -144], 377, "minecraft:blaze_powder", []],
  [[-208, -160], 378, "minecraft:magma_cream", []],
  [[-192, -160], 379, "minecraft:brewing_stand", []],
  [[-192, -144], 380, "minecraft:cauldron", []],
  [[-176, -144], 381, "minecraft:ender_eye", []],
  [[-144, -128], 382, "minecraft:speckled_melon", []],
  [[-160, -224], 383, "minecraft:spawn_egg", ["N"]],
  [[-176, -160], 384, "minecraft:experience_bottle", []],
  [[-224, -32], 385, "minecraft:fire_charge", []],
  [[-176, -176], 386, "minecraft:writable_book", []],
  [[-192, -176], 387, "minecraft:written_book", []],
  [[-160, -176], 388, "minecraft:emerald", []],
  [[-224, -192], 389, "minecraft:item_frame", []],
  [[-208, -176], 390, "minecraft:flower_pot", []],
  [[-128, -112], 391, "minecraft:carrot", []],
  [[-112, -112], 392, "minecraft:potato", []],
  [[-96, -112], 393, "minecraft:baked_potato", []],
  [[-96, -128], 394, "minecraft:poisonous_potato", []],
  [[-208, -192], 395, "minecraft:map", []],
  [[-96, -144], 396, "minecraft:golden_carrot", []],
  [[-352, -144], 397, "minecraft:skull", ["B"]],
  [[-96, -96], 398, "minecraft:carrot_on_a_stick", ["D"]],
  [[-144, -176], 399, "minecraft:nether_star", []],
  [[-128, -144], 400, "minecraft:pumpkin_pie", []],
  [[-144, -192], 401, "minecraft:fireworks", []],
  [[-160, -192], 402, "minecraft:firework_charge", []],
  [[-240, -192], 403, "minecraft:enchanted_book", []],
  [[-80, -144], 404, "minecraft:comparator", []],
  [[-80, -160], 405, "minecraft:netherbrick", []],
  [[-192, -192], 406, "minecraft:quartz", []],
  [[-112, -176], 407, "minecraft:tnt_minecart", []],
  [[-112, -192], 408, "minecraft:hopper_minecart", []],
  [[-80, -192], 409, "minecraft:prismarine_shard", []],
  [[-96, -192], 410, "minecraft:prismarine_crystals", []],
  [[-144, -208], 411, "minecraft:rabbit", []],
  [[-96, -224], 412, "minecraft:cooked_rabbit", []],
  [[-128, -224], 413, "minecraft:rabbit_stew", []],
  [[-112, -224], 414, "minecraft:rabbit_foot", []],
  [[-64, -224], 415, "minecraft:rabbit_hide", []],
  [[0, -208], 416, "minecraft:armor_stand", []],
  [[-32, -144], 417, "minecraft:iron_horse_armor", []],
  [[-64, -144], 418, "minecraft:golden_horse_armor", []],
  [[-48, -144], 419, "minecraft:diamond_horse_armor", []],
  [[0, -144], 420, "minecraft:lead", []],
  [[0, -160], 421, "minecraft:name_tag", []],
  [[-112, -208], 422, "minecraft:command_block_minecart", []],
  [[-144, -224], 423, "minecraft:mutton", []],
  [[-80, -224], 424, "minecraft:cooked_mutton", []],
  [[-96, -320], 425, "minecraft:banner", []],
  [[-224, -256], 426, "minecraft:end_crystal", []],
  [[-80, -208], 427, "minecraft:spruce_door", []],
  [[-32, -208], 428, "minecraft:birch_door", []],
  [[-64, -208], 429, "minecraft:jungle_door", []],
  [[-16, -208], 430, "minecraft:acacia_door", []],
  [[-48, -208], 431, "minecraft:dark_oak_door", []],
  [[-160, -208], 432, "minecraft:chorus_fruit", []],
  [[-176, -208], 433, "minecraft:chorus_fruit_popped", []],
  [[-64, -160], 434, "minecraft:beetroot", []],
  [[-48, -160], 435, "minecraft:beetroot_seeds", []],
  [[-96, -160], 436, "minecraft:beetroot_soup", []],
  [[-144, -160], 437, "minecraft:dragon_breath", []],
  [[-160, -144], 438, "minecraft:splash_potion", []],
  [[-96, -208], 439, "minecraft:spectral_arrow", []],
  [[-176, -192], 440, "minecraft:tipped_arrow", []],
  [[-144, -144], 441, "minecraft:lingering_potion", []],
  [[-192, -208], 442, "minecraft:shield", []],
  [[-96, -256], 443, "minecraft:elytra", []],
  [[-16, -256], 444, "minecraft:spruce_boat", []],
  [[-32, -256], 445, "minecraft:birch_boat", []],
  [[-48, -256], 446, "minecraft:jungle_boat", []],
  [[-64, -256], 447, "minecraft:acacia_boat", []],
  [[-80, -256], 448, "minecraft:dark_oak_boat", []],
  [[-128, -272], 449, "minecraft:totem_of_undying", []],
  [[-112, -272], 450, "minecraft:shulker_shell", []],
  [[-240, -272], 452, "minecraft:iron_nugget", []],
  [[0, -288], 453, "minecraft:knowledge_book", []],
  [[0, -240], 2256, "minecraft:record_13", []],
  [[-16, -240], 2257, "minecraft:record_cat", []],
  [[-32, -240], 2258, "minecraft:record_blocks", []],
  [[-48, -240], 2259, "minecraft:record_chirp", []],
  [[-64, -240], 2260, "minecraft:record_far", []],
  [[-80, -240], 2261, "minecraft:record_mall", []],
  [[-96, -240], 2262, "minecraft:record_mellohi", []],
  [[-112, -240], 2263, "minecraft:record_stal", []],
  [[-128, -240], 2264, "minecraft:record_strad", []],
  [[-144, -240], 2265, "minecraft:record_ward", []],
  [[-160, -240], 2266, "minecraft:record_11", []],
  [[-176, -240], 2267, "minecraft:record_wait", []]
];

export const overrides = [
  ["minecraft:plank","Oak_Wood_Axis_Y_JE1_BE1.png","Spruce_Wood_Axis_Y_JE1_BE1.png","Birch_Wood_Axis_Y_JE1_BE1.png","Jungle_Wood_Axis_Y_JE1_BE1.png","Acacia_Wood_Axis_Y_JE2_BE1.png","Dark_Oak_Wood_Axis_Y_JE2_BE1.png"],
  ["minecraft:stone","Stone_JE2_BE1.png","Granite_JE1_BE1.png","Polished_Granite_JE1_BE1.png","Diorite_JE1_BE1.png","Polished_Diorite_JE1_BE1.png","Andesite_JE1_BE1.png","Polished_Andesite_JE1_BE1.png"],
  ["minecraft:dirt","Dirt_JE2_BE1.png","Coarse_Dirt_JE1_BE1.png","Podzol_JE1_BE1.png"],
  ["minecraft:sapling","Oak_Sapling_JE4_BE1.png","Spruce_Sapling_JE1_BE1.png","Birch_Sapling_JE1_BE1.png","Jungle_Sapling_JE1_BE1.png","Acacia_Sapling_JE1_BE1.png","Dark_Oak_Sapling_JE1_BE1.png"],
  ["minecraft:sand","Sand_JE3_BE1.png","Red_Sand_JE1_BE1.png"],
  ["minecraft:log","Oak_Wood_Axis_Y_JE1_BE1.png","Spruce_Wood_Axis_Y_JE1_BE1.png","Birch_Wood_Axis_Y_JE1_BE1.png","Jungle_Wood_Axis_Y_JE1_BE1.png"],
  ["minecraft:log2","Acacia_Wood_Axis_Y_JE2_BE1.png","Dark_Oak_Wood_Axis_Y_JE2_BE1.png"],
  ["minecraft:leaves","Oak_Leaves_JE3_BE1.png","Spruce_Leaves_JE1_BE1.png","Birch_Leaves_JE1_BE2.png","Jungle_Leaves_JE1_BE1.png"],
  ["minecraft:leaves2","Acacia_Leaves_JE2.png","Dark_Oak_Leaves_JE2.png"],
  ["minecraft:carpet","White_Carpet.png","Orange_Carpet.png","Magenta_Carpet.png","Light_Blue_Carpet.png","Yellow_Carpet.png","Lime_Carpet.png","Pink_Carpet.png","Gray_Carpet.png","Light_Gray_Carpet.png","Cyan_Carpet.png","Purple_Carpet.png","Blue_Carpet.png","Brown_Carpet.png","Green_Carpet.png","Red_Carpet.png","Black_Carpet.png"],
  ["minecraft:wool","White_Wool.png","Orange_Wool.png","Magenta_Wool.png","Light_Blue_Wool.png","Yellow_Wool.png","Lime_Wool.png","Pink_Wool.png","Gray_Wool.png","Light_Gray_Wool.png","Cyan_Wool.png","Purple_Wool.png","Blue_Wool.png","Brown_Wool.png","Green_Wool.png","Red_Wool.png","Black_Wool.png"],
  ["minecraft:stained_hardened_clay","White_Terracotta_JE1_BE1.png","Orange_Terracotta_JE1_BE1.png","Magenta_Terracotta_JE1_BE1.png","Light_Blue_Terracotta_JE1_BE1.png","Yellow_Terracotta_JE1_BE1.png","Lime_Terracotta_JE1_BE1.png","Pink_Terracotta_JE1_BE1.png","Gray_Terracotta_JE1_BE1.png","Light_Gray_Terracotta_JE1_BE1.png","Cyan_Terracotta_JE1_BE1.png","Purple_Terracotta_JE1_BE1.png","Blue_Terracotta_JE1_BE1.png","Brown_Terracotta_JE1_BE1.png","Green_Terracotta_JE1_BE1.png","Red_Terracotta_JE1_BE1.png","Black_Terracotta_JE1_BE1.png"],
  ["minecraft:stained_glass","White_Stained_Glass.png","Orange_Stained_Glass.png","Magenta_Stained_Glass.png","Light_Blue_Stained_Glass.png","Yellow_Stained_Glass.png","Lime_Stained_Glass.png","Pink_Stained_Glass.png","Gray_Stained_Glass.png","Light_Gray_Stained_Glass.png","Cyan_Stained_Glass.png","Purple_Stained_Glass.png","Blue_Stained_Glass.png","Brown_Stained_Glass.png","Green_Stained_Glass.png","Red_Stained_Glass.png","Black_Stained_Glass.png"],
  ["minecraft:stone_slab","Smooth_Stone_Slab_JE2_BE2.png","Sandstone_Slab_JE5_BE2.png","Oak_Slab_JE5_BE2.png","Cobblestone_Slab_JE4_BE2.png","Brick_Slab_JE3_BE2.png","Stone_Brick_Slab_JE3_BE2.png","Nether_Brick_Slab_JE3_BE3.png","Quartz_Slab_JE3_BE2.png"],
  ["minecraft:stone_slab2","Red_Sandstone_Slab_JE4_BE2.png"],
  ["minecraft:wooden_slab","Oak_Slab_JE5_BE2.png","Spruce_Slab_JE4_BE2.png","Birch_Slab_JE3_BE2.png","Jungle_Slab_JE3_BE2.png","Acacia_Slab_JE3_BE2.png","Dark_Oak_Slab_JE3_BE2.png"],
  ["minecraft:sandstone","Sandstone_JE2_BE1.png","Chiseled_Sandstone_JE1_BE1.png","Smooth_Sandstone_Slab_JE3_BE2.png"],
  ["minecraft:red_sandstone","Red_Sandstone_JE1_BE1.png","Chiseled_Red_Sandstone_JE1_BE1.png","Smooth_Red_Sandstone.png"],
  ["minecraft:tallgrass","Tall_Grass_JE1_BE1.png","Fern_JE1_BE1.png"],
  ["minecraft:red_flower","Poppy_JE1_BE1.png","Blue_Orchid_JE1_BE1.png","Allium_JE1_BE1.png","Azure_Bluet_JE1_BE1.png","Red_Tulip_JE1_BE1.png","Orange_Tulip_JE1_BE1.png","White_Tulip_JE1_BE1.png","Pink_Tulip_JE1_BE1.png","Oxeye_Daisy_JE1_BE1.png"],
  ["minecraft:double_plant","Sunflower_JE1_BE1.png","Lilac_JE1_BE1.png","Tall_Grass_JE1_BE1.png","Fern_JE1_BE1.png","Rose_Bush_JE1_BE1.png","Peony_JE1_BE1.png"],
  ["minecraft:monster_egg","Stone_JE2_BE1.png","Cobblestone_JE4_BE2.png","Stone_Bricks_JE1_BE1.png","Mossy_Stone_Bricks_JE1_BE1.png","Cracked_Stone_Bricks_JE1_BE1.png","Chiseled_Stone_Bricks_JE1_BE1.png"],
  ["minecraft:stonebrick","Stone_Bricks_JE1_BE1.png","Mossy_Stone_Bricks_JE1_BE1.png","Cracked_Stone_Bricks_JE1_BE1.png","Chiseled_Stone_Bricks_JE1_BE1.png"],
  ["minecraft:prismarine","Prismarine_JE1_BE1.gif","Dark_Prismarine_JE1_BE1.png","Prismarine_Bricks_JE1_BE1.png"],
  ["minecraft:sponge","Sponge_JE2_BE2.png","Wet_Sponge_JE1_BE1.png"],
  ["minecraft:cobblestone_wall","Cobblestone_Wall.png","Mossy_Cobblestone_Wall.png"],
  ["minecraft:skull","Skeleton_Skull.png","Wither_Skeleton_Skull.png","Zombie_Head.png","Player_Head.png","Creeper_Head.png","Dragon_Head.png"],
  ["minecraft:coal","Coal_JE3_BE2.png","Charcoal_JE3_BE3.png"],
  ["minecraft:dye","Ink_Sac_JE1_BE1.png","Red_Dye_JE1_BE1.png","Green_Dye_JE1_BE1.png","Cocoa_Beans_JE3_BE1.png","Lapis_Lazuli_JE1_BE1.png","Purple_Dye_JE1_BE1.png","Cyan_Dye_JE1_BE1.png","Light_Gray_Dye_JE2_BE2.png","Gray_Dye_JE1_BE1.png","Pink_Dye_JE1_BE1.png","Lime_Dye_JE1_BE1.png","Yellow_Dye_JE1_BE1.png","Light_Blue_Dye_JE1_BE1.png","Magenta_Dye_JE1_BE1.png","Orange_Dye_JE1_BE1.png","Bone_Meal_JE1_BE1.png"],
  ["minecraft:fish","Raw_Cod_JE1_BE1.png","Raw_Salmon_JE2_BE2.png","Tropical_Fish_JE2_BE2.png","Pufferfish_JE3_BE2.png"],
  ["minecraft:cooked_fish","Cooked_Cod_JE2_BE2.png","Cooked_Salmon_JE2_BE2.png"],
  ["minecraft:golden_apple","Golden_Apple_JE1_BE1.png","Enchanted_Golden_Apple_JE1_BE1.gif"]
];
